version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/frontend"
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
#Test
