version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.15.4/terraform_0.15.4_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/terraform"
      - BUILD_DATE=$(date "+%s")
      - aws s3 mv s3://$TERRAFORM_STATE_BUCKET/terraform.tfstate s3://$TERRAFORM_STATE_BUCKET/$BUILD_DATE-terraform.tfstate
      - aws s3 cp s3://$TERRAFORM_STATE_BUCKET/$BUILD_DATE-terraform.tfstate terraform.tfstate
      - terraform init
      - terraform apply -auto-approve

  post_build:
    commands:
      - aws s3 mv terraform.tfstate s3://$TERRAFORM_STATE_BUCKET/terraform.tfstate
      - echo "Terraform completed!"
#Test
